name: Deploy to Netlify (Prod)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug; Check if env variables are set
        run: |
          if [ -z "$NETLIFY_AUTH_TOKEN" ]; then
            echo "❌ NETLIFY_AUTH_TOKEN is not set"
            exit 1
          else
            echo "✅ NETLIFY_AUTH_TOKEN is set"
          fi

          if [ -z "$NETLIFY_SITE_ID" ]; then
            echo "❌ NETLIFY_SITE_ID is not set"
            exit 1
          else
            echo "✅ NETLIFY_SITE_ID is set"
          fi
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Install Netlify CLI globally
        run: npm install -g netlify-cli

      - name: Deploy to production (main branch)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: netlify deploy --prod --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy preview (pull request)
        if: github.event_name == 'pull_request'
        run: netlify deploy --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

